name: Pull request checks

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.cfengine }} / ColdBox ${{ matrix.coldboxVersion }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        cfengine:
          - lucee@6
          - lucee@7
          - adobe@2023
          - adobe@2025
          - boxlang-cfml@1
          - boxlang@1
        coldboxVersion:
          - ^8.1.0
        experimental:
          - false
        include:
          # - cfengine: lucee@be
          #   coldboxVersion: be
          #   experimental: true
          - cfengine: adobe@be
            coldboxVersion: be
            experimental: true
          - cfengine: boxlang@be
            coldboxVersion: be
            experimental: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21

      - name: Set up CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install CommandBox BoxLang support
        run: box install commandbox-boxlang

      - name: Install dependencies
        run: |
          box install
          cd test-harness
          box package set dependencies.coldbox=${{ matrix.coldboxVersion }}
          box install

      - name: Start ${{ matrix.cfengine }} server
        run: |
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --noSaveSettings
          curl --fail --retry 12 --retry-delay 5 --retry-connrefused http://127.0.0.1:8520/

      - name: Run TestBox tests
        run: box testbox run
